export default [
	{ id: 1, img: "./src/assets/Frame 151 (1).svg" },
	{ id: 2, img: "./src/assets/Frame 151 (2).svg" },
	{ id: 3, img: "./src/assets/Frame 151 (3).svg" },
	{ id: 4, img: "./src/assets/Frame 151 (4).svg" },
	{ id: 5, img: "./src/assets/Frame 151 (5).svg" },
	{ id: 6, img: "./src/assets/Frame 151 (6).svg" },
	{ id: 7, img: "./src/assets/Frame 151 (7).svg" },
	{ id: 8, img: "./src/assets/Frame 151 (8).svg" },
]
// [
// 	{ img: "./src/assets/Frame 151 (1).svg" },
// 	{ img: "./src/assets/Frame 151 (2).svg" },
// 	{ img: "./src/assets/Frame 151 (3).svg" },
// 	{ img: "./src/assets/Frame 151 (4).svg" },
// 	{ img: "./src/assets/Frame 151 (5).svg" },
// 	{ img: "./src/assets/Frame 151 (6).svg" },
// 	{ img: "./src/assets/Frame 151 (7).svg" },
// 	{ img: "./src/assets/Frame 151 (8).svg" },
// 	{ img: "./src/assets/Frame 151 (9).svg" },
// 	{ img: "./src/assets/Frame 151 (10).svg" },
// 	{ img: "./src/assets/Frame 151 (11).svg" },
// 	{ img: "./src/assets/Frame 151 (12).svg" },
// 	{ img: "./src/assets/Frame 151 (13).svg" },
// 	{ img: "./src/assets/Frame 151 (14).svg" },
// 	{ img: "./src/assets/Frame 151.svg" },
// ];
